[package]
name = "uefi-rand"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
rand_core = "0.6.4"
uefi = "0.30.0"

[lints.clippy]
pedantic = "warn"
nursery = "warn"
module-name-repetitions = "allow"
